Hw 4
Fedich09/DAO_3 pull request #2
Opened 2021-01-12 19:08 UTC by Fedich09

2021-01-12 19:34 UTC, Ketch92 requested changes

2021-01-12 19:34 UTC, Ketch92 commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +                .orElseThrow(() -> new RuntimeException("Car not exist!"));
a grammatical error in the message "Car doesn't exist!"

2021-01-12 19:34 UTC, Ketch92 commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +        }
hmmm... I would suggest using streams here

2021-01-12 19:34 UTC, Ketch92 commented on src/main/java/mate/dao/impl/DriverDaoImpl.java
> +                .orElseThrow(() -> new RuntimeException("Drive not exist!"));
message "Driver doesn't exist!"

2021-01-12 22:34 UTC, Fedich09 commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +        }
Good idea, I tried, but  I couldn't

2021-01-13 06:58 UTC, Ketch92 approved these changes

2021-01-13 09:18 UTC, RomanDubovskyi requested changes

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/service/impl/DriverServiceImpl.java
> +    DriverDao driverDao;
access modifiers

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +    public Car get(Long id) {
we should return optional from dao layer

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +    public void addDriverToCar(Driver driver, Car car) {
this method should be on the service layer

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +    public void removeDriverFromCar(Driver driver, Car car) {
same here

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +        }
return Storage.cars.stream()
                .filter(c -> c.getDrivers().stream()
                    .anyMatch(d -> d.getId().equals(driverId)))
                .collect(Collectors.toList());

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/DriverDaoImpl.java
> +    public Driver get(Long id) {
same here

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/service/ManufacturerService.java
> +public interface ManufacturerService {
this file is from prev hw, it should not be in current PR

2021-01-13 09:18 UTC, RomanDubovskyi commented on src/main/java/mate/service/impl/CarServiceImpl.java
> +    CarDao carDao;
what about access modifiers

2021-01-13 11:09 UTC, RomanDubovskyi requested changes
if you merge this PR, you will loose ManufacturerService from master. We don't want to delete those files from the project, point is that these files should not be in the PR. 
You probably have created PR wrongly. Try to open PR with changes that are related only to this hw

2021-01-13 11:09 UTC, RomanDubovskyi commented on src/main/java/mate/dao/impl/CarDaoImpl.java
> +                        .anyMatch(d -> d.getId() != null && d.getId().equals(driverId)))
this is optional, but better to use Objects.equals

2021-01-13 11:09 UTC, RomanDubovskyi commented on src/main/java/mate/service/impl/CarServiceImpl.java
> +        carDao.update(car);
```suggestion
        car.getDrivers().remove(driver);
        carDao.update(car);
```
same with the add

2021-01-13 13:10 UTC, closed without merging